language: swift
podfile: Example/Podfile

osx_image: xcode10
xcode_sdk: iphonesimulator11.0

before_install:
  - rvm use system
  - brew install ruby
  - sudo gem install cocoapods -v '1.5.0'
  - pod repo update

script:
- xcodebuild clean build test -workspace Example/DKImagePickerControllerDemo.xcworkspace -scheme DKImagePickerControllerDemo -destination "platform=iOS Simulator,name=iPhone 7"
